version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      
    ports:
      - "5432:5432"
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ../../postgresql_data:/var/lib/postgresql/data
    networks:
      - taskmaster-net
    
    

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - taskmaster-net

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD=changeme
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  #   networks:
  #     - taskmaster-net

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - taskmaster-net

volumes:
  postgres_data:
  es_data:

networks:
  taskmaster-net:
    driver: bridge